# Generated by Django 3.1.7 on 2021-03-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitas',
            old_name='id_receita',
            new_name='id_recipe',
        ),
        migrations.RenameField(
            model_name='receitas',
            old_name='receita',
            new_name='recipe',
        ),
    ]
