# Generated by Django 3.1.7 on 2021-03-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_auto_20210319_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='preparation_time',
            field=models.CharField(max_length=50, verbose_name='tempo de preparo'),
        ),
    ]
